
[package]
name = "sol_square"
version = "0.0.1"
edition = "2021"
license = "unlicense"
publish = false


[dependencies]
solana-program = "=1.18.12"
borsh = "1.5.0"
toml_edit = "=0.21.0"

[lib]
crate-type = ["cdylib", "lib"]
path = "src/lib.rs"
